version: '3.3'
services:
  wireguard:
    build: .
    cap_add:
     - NET_ADMIN
    volumes:
     - ./wireguard:/etc/wireguard
     - ./entrypoint.sh:/entrypoint.sh
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=info
     - PORT=3004
     - SERVER=s1:80
    restart: always

  s1:
    image: nginx:latest
    container_name: s1
    volumes:
      - ./example/s1:/usr/share/nginx/html
