version: '3.3'
services:
  wireguard:
    build: .
    cap_add:
     - NET_ADMIN
    volumes:
     - ./wireguard:/etc/wireguard
     - ./entrypoint.sh:/entrypoint.sh
    environment:
     - PORT=3004
     - SERVER=web:80
    restart: always
    depends_on:
     - web

  web:
    image: nginx
