version: '3.3'
services:
  wireguard:
    build: .
    cap_add:
     - NET_ADMIN
    environment:
     - SERVER=web:80
     - WG_ENDPOINT=192.168.121.39:51820
     - WG_PRIVATE=+MYPa0mJ7PSWR2lxl0gN6uQNmLPZc2kGXnXoUVtnTmk=
     - WG_PUBLIC=CpC/jovtd6WcZM9tD51LIT4M9hf/ey9FlD3jrr/Cow8=
    restart: always
    depends_on:
     - web

  web:
    image: nginx
