version: '3.3'
services:
  wireguard:
    build: .
    cap_add:
     - NET_ADMIN
     - SYS_MODULE
    sysctls:
     - net.ipv4.ip_forward=1
     - net.ipv4.conf.all.src_valid_mark=1
    volumes:
     - /dev/net/tun:/dev/net/tun
     - ./wireguard:/etc/wireguard
     - ./entrypoint.sh:/entrypoint.sh
     - ./example/s1:/usr/share/nginx/html
    environment:
     - WG_COLOR_MODE=always
     - LOG_LEVEL=info
     - PORT=3004
     - SERVER=s1:80
    ports:
     - 51820:51820/udp
    # Uncomment the following line when 'AllowedIPs' is '0.0.0.0/0'
    # privileged: true
    restart: always

  s1:
    image: nginx:latest
    container_name: s1
    volumes:
      - ./example/s1:/usr/share/nginx/html
    ports:
      - 0.0.0.0:3001:80
